# Generated by Django 4.0.4 on 2024-07-19 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('-created_at',)},
        ),
    ]
